### PR TITLE
[NEW MODULE] AutoMLG Hack 👍 

### PR DESCRIPTION
**Pull request by PiotrekUnityDeveloper**
A new module called AutoMLG which makes the player do mlg buckets automatically to avoid fall damage
image
**Note:** Allow inventory option is currently not avaiable due to crashing minecraft while trying to use it (idk why, tho ill try to fix that)
more clear explanation of what the mode does:

https://user-images.githubusercontent.com/85606121/160497769-002677c8-3395-4652-bf94-aaf247e55d8e.mp4

thanks :D

### CODE REVIEW

**Comment by PiotrekUnityDeveloper** [comment]
i know theres already NoFall Bucket but AutoMLG is more legit and has support for powdered snow 👍

**Comment by PiotrekUnityDeveloper** [comment]
For people that wants a developement build of the client with this module (AutoMLG), here u are:
[https://www.mediafire.com/file/b2a8uh25biq5w8c/MatHax-1.7.4.jar/file](url)
if u dont trust me, u can go here for the source code and build the dev build urself:
[https://github.com/PiotrekUnityDeveloper/Client](url)

**Comment by QuartzWarrior** [comment]
Ladder clutch?

**Comment by PiotrekUnityDeveloper** [comment]
only mlg water bucket/powder snow for now

**Pull request merged**
